[assembly: System.Reflection.AssemblyCompanyAttribute("BarebonesAutoMapperIntegration.Service.Tests")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("BarebonesAutoMapperIntegration.Service.Tests")]
[assembly: System.Reflection.AssemblyTitleAttribute("BarebonesAutoMapperIntegration.Service.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]